#!/bin/sh

git log -1 --format=%s HEAD|grep -q "^AUTOBOT-VERSIONING: " && exit

DATE=$(date -u "+%Y-%m-%dT%H:%M:%S")

cp commit-version.txt commit-version-tmp.txt

awk 'BEGIN{ FS=OFS=":" }
/#COMMIT REVISION:/{ match($NF, /^[0-9]+/); $NF=($NF+1) substr($NF, RLENGTH+1) }1' commit-version.txt > commit-version-tmp.txt

sed -i'' -E "s/^#COMMIT DATETIME - LAST MODIFIED:.*$/#COMMIT DATETIME - LAST MODIFIED: $DATE/" commit-version-tmp.txt

cp commit-version-tmp.txt commit-version.txt
rm commit-version-tmp.txt*

git add commit-version.txt

git diff-index --quiet --cached HEAD || git commit -m "AUTOBOT-VERSIONING: Update Commit Version"
