repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: fix-encoding-pragma
    -   id: check-json
    -   id: pretty-format-json
    -   id: requirements-txt-fixer
    -   id: check-case-conflict
    -   id: check-builtin-literals
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
# repos:
#     repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v2.3.0
#     hooks:
#         id: check-yaml
#         id: check-ast
#         id: end-of-file-fixer
#         id: trailing-whitespace
#         id: fix-encoding-pragma
#         id: check-json
#         id: pretty-format-json
#         id: end-of-file-fixer
#         id: requirements-txt-fixer
#         id: check-case-conflict
#         id: check-builtin-literals
#         id: check-added-large-files

#     repo: https://github.com/psf/black
#     rev: 21.12b0
#     hooks:
#         id: black
