#!/bin/sh

git log -1 --format=%s HEAD|grep -q "^BOT-VERSIONING: " && exit

date -u > commit-version.txt


git diff-index --quiet --cached HEAD || git commit -m "BOT-VERSIONING: lastmod"

DATE=$(date -u "+%Y-%m-%dT%H:%M:%S")

sed -i -e "s/^#COMMIT DATETIME - LAST MODIFIED:.*$/#COMMIT DATETIME - LAST MODIFIED: $DATE/" commit-version.txt

git add commit-version.txt


FILES=$(git diff --name-only HEAD^ HEAD|grep -x 'foo/.*\.html')
grep -xl "$START.*$END" $FILES < /dev/null |\
while read file;
do
    DATE=$(date '+%Y-%m-%d')
    sed -i "s,^\($START\).*\($END\),\1$DATE\2," $file &&
    git add $file
done

git diff-index --quiet --cached HEAD || git commit -m "BOT-VERSIONING: lastmod"